# Generated by Django 4.2.3 on 2023-07-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_alter_pais_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='editoriales/')),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
